name: User Feedback
description: Provide feedback or report issues for Hydrate Move
title: "User Feedback - [Brief description]"
labels: ["user-feedback", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Hydrate Move! Your feedback helps us improve the application.
        
  - type: checkboxes
    id: feedback-type
    attributes:
      label: Feedback Type
      description: What type of feedback are you providing?
      options:
        - label: Feature suggestion
        - label: Bug report
        - label: User experience feedback
        - label: General comment

  - type: textarea
    id: description
    attributes:
      label: Detailed Description
      description: Please describe your feedback in detail
      placeholder: Tell us what you think...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior (for bugs/features)
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior (for bugs)
      description: What actually happened?
      placeholder: Describe what actually happened...

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      placeholder: e.g., Chrome 120.0.0.0

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      placeholder: e.g., Windows 11, macOS 14.0

  - type: input
    id: screen-resolution
    attributes:
      label: Screen Resolution
      description: What's your screen resolution?
      placeholder: e.g., 1920x1080

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information you'd like to share?
      placeholder: Add any additional context, screenshots, or examples...